doctrine_migrations:
    migrations_paths:
        'App\Modules\Authentication\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Authentication/Infrastructure/Persistence'
        'App\Modules\Billing\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Billing/Infrastructure/Persistence'
    enable_profiler: false
