doctrine_migrations:
    migrations_paths:
        'App\Modules\User\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/User/Infrastructure/Persistence'
        'App\Modules\Client\Infrastructure\Persistence': '%kernel.project_dir%/src/Modules/Client/Infrastructure/Persistence'
    enable_profiler: false
