
ping:
    path: api/ping
    controller: App\PingController

auth_api:
    prefix: api/auth
    name_prefix: auth.
    resource: '../src/Modules/Authentication/Infrastructure/Http/routes.yml'

job_api:
    prefix: api
    name_prefix: job.
    resource: '../src/Modules/Job/Infrastructure/Http/routes.yml'

candidate_api:
    prefix: api
    name_prefix: candidate.
    resource: '../src/Modules/Candidate/Infrastructure/Http/routes.yml'

billing_api:
    prefix: api/billing/
    name_prefix: billing.
    resource: '../src/Modules/Billing/Infrastructure/Http/routes.yml'

