
store:
  methods: [POST]
  path: job
  controller: App\Modules\Job\Infrastructure\Http\Controller\StoreJobController

get_job:
  methods: [GET]
  path: job/{jobId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\GetJobController
