
job.store:
  methods: [POST]
  path: job
  controller: App\Modules\Job\Infrastructure\Http\Controller\StoreJobController

job.close:
  methods: [PATCH]
  path: job/{jobId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\CloseJobController

job_post.store:
  methods: [POST]
  path: job/{jobId}/jobPost
  controller: App\Modules\Job\Infrastructure\Http\Controller\StoreJobPostController

job_post.apply:
  methods: [POST]
  path: job/{jobId}/jobPost/{jobPostId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\ApplyOnJobPostController

job_post.close:
  methods: [PATCH]
  path: job/{jobId}/jobPost/{jobPostId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\CloseJobPostController

job_post.fetch:
  methods: [GET]
  path: job/{jobId}/jobPost/{jobPostId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\GetJobPostController

job_post.fetch_all:
  methods: [GET]
  path: jobPost
  controller: App\Modules\Job\Infrastructure\Http\Controller\GetJobPostsController

category.store:
  methods: [POST]
  path: job/category
  controller: App\Modules\Job\Infrastructure\Http\Controller\StoreJobCategoryController

category.fetch_all:
  methods: [GET]
  path: job/category
  controller: App\Modules\Job\Infrastructure\Http\Controller\GetJobCategoriesController

company.store:
  methods: [POST]
  path: job/company
  controller: App\Modules\Job\Infrastructure\Http\Controller\StoreCompanyController

job.get:
  methods: [GET]
  path: job/{jobId}
  controller: App\Modules\Job\Infrastructure\Http\Controller\GetJobController
